#!/data/data/com.termux/files/usr/bin/bash
clear

#===============================================================
#   HYDRAX HYPERSENSE – MASTER INSTALLER
#   setup.sh – Complete Zero-Bug Full Install
#   Branding: HYDRAX HYPERSENSE™
#   Beta Tester: RC DEMON
#   Developer: HydraxHyperSense
#   Version: v10-Stable
#===============================================================

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "           HYDRAX HYPERSENSE™ – SETUP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Preparing your device…"
echo " Beta Tester: RC DEMON"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
sleep 1

#===============================================================
#   STEP A – UPDATE PACKAGE MANAGER
#===============================================================
echo ""
echo "[A] Updating Termux package database…"
pkg update -y && pkg upgrade -y

#===============================================================
#   STEP B – INSTALL REQUIRED PACKAGES
#===============================================================
echo ""
echo "[B] Installing core system dependencies…"

pkg install -y bash python git curl wget
pkg install -y proot tsu openssl-tool termux-api
pkg install -y util-linux coreutils grep sed findutils
pkg install -y ncurses-utils procps

echo "[✔] Base dependencies installed."

#===============================================================
#   STEP C – INSTALL TERMUX SERVICES (FOR BOOT / BACKGROUND)
#===============================================================
echo ""
echo "[C] Installing Termux Services (daemon support)…"
pkg install -y termux-services

echo "[✔] Termux Services ready."

#===============================================================
#   STEP D – CREATE HYPERSENSE FOLDER STRUCTURE
#===============================================================
echo ""
echo "[D] Creating Hypersense filesystem…"

mkdir -p $PREFIX/opt/hypersense/
mkdir -p $PREFIX/var/hypersense/
mkdir -p $PREFIX/var/hypersense/logs/
mkdir -p $PREFIX/var/hypersense/engine/
mkdir -p ~/.termux/boot/

echo "[✔] Directories created."

#===============================================================
#   STEP E – GIT CLONE / COPY HYPERSENSE FILES
#===============================================================
echo ""
echo "[E] Checking Hypersense source location…"

read -p "Do you want to clone from GitHub? (y/n): " cloneChoice

if [ "$cloneChoice" == "y" ]; then
    echo "[+] Enter GitHub Repo URL (your Hypersense repo):"
    read repoURL

    echo "[+] Cloning repository…"
    git clone $repoURL $PREFIX/opt/hypersense/

    if [ $? -ne 0 ]; then
        echo "[✖] Git clone failed! Check URL or network."
        exit 1
    fi

    echo "[✔] Hypersense cloned successfully."

else
    echo "[+] Skipping git clone."
    echo "[!] Place your HypersenseFinal_Stable.sh manually in:"
    echo "     $PREFIX/opt/hypersense/"
    sleep 2
fi

#===============================================================
#   STEP F – INSTALL REQUIREMENTS SCRIPT
#===============================================================
echo ""
echo "[F] Generating install_requirements.sh…"

cat <<EOF > $PREFIX/opt/hypersense/install_requirements.sh
#!/data/data/com.termux/files/usr/bin/bash
# Auto-generated by setup.sh
bash setup_requirements_auto.sh
EOF

chmod +x $PREFIX/opt/hypersense/install_requirements.sh

echo "[✔] install_requirements.sh ready."

#===============================================================
#   STEP G – GENERATE ENGINE WORKER (PLACEHOLDER)
#===============================================================
echo ""
echo "[G] Preparing engine worker service…"

cat <<EOF > $PREFIX/opt/hypersense/engine_worker.sh
#!/data/data/com.termux/files/usr/bin/bash
# HYDRAX HYPERSENSE AI ENGINE (Auto-generated)
while true; do
    sleep 5
done
EOF

chmod +x $PREFIX/opt/hypersense/engine_worker.sh

echo "[✔] Engine service created."

#===============================================================
#   STEP H – CREATE BOOT SCRIPT
#===============================================================
echo ""
echo "[H] Creating boot service script…"

cat <<EOF > ~/.termux/boot/hypersense_boot.sh
#!/data/data/com.termux/files/usr/bin/bash
bash $PREFIX/opt/hypersense/engine_worker.sh &
EOF

chmod +x ~/.termux/boot/hypersense_boot.sh

echo "[✔] Boot script deployed."

#===============================================================
#   STEP I – FINAL MESSAGE
#===============================================================

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "         HYDRAX HYPERSENSE SETUP COMPLETE!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run the main tool with:"
echo "     bash HypersenseFinal_Stable.sh"
echo ""
echo "Engine Runner Installed."
echo "Branding + Credits Added."
echo "Beta Tester Included: RC DEMON"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
exit 0
